export const CHANGE_SERACH_FIELD ="CHANGE_SERACH_FIELD"

export const REQUEST_ROBOTS_PENDING = "REQUEST_ROBOTS_PENDING"

export const REQUEST_ROBOTS_SUCCESS= "REQUEST_ROBOTS_SUCCESS"

export const REQUEST_ROBOTS_FAILURE = "REQUEST_ROBOTS_FAILURE"